INSERT INTO customers (username, password, fname, lname, dodid, phone_number, meal_card, is_admin, karma_score, email, profile_pic) VALUES 
    ('customer1', 'password1', 'Sylvia', 'Plath', '1234567890', '808-080-8080', TRUE, FALSE, 10, 'splath@fake.com', NULL),
    ('customer2', 'password2', 'Anne', 'Sexton', '9987654321', '917-123-4343', FALSE, TRUE, 20, 'asexton@fake.com', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png'),
    ('customer3', 'password3', 'Bilbo', 'Baggins', '9999887777', '808-123-5533', TRUE, FALSE, 15, 'baggins@fake.com', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png'),
    ('customer4', 'password4', 'Arthur', 'Pendragon', '1111155555', '213-321-4321', TRUE, FALSE, 20, 'kingart@fake.com', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png'),
    ('customer5', 'password5', 'Auntie', 'Ursula', '1234565432', '808-999-5678', FALSE, FALSE, 5, 'ursula@fake.com', 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png');

INSERT INTO dfacs (dfac_name, dfac_logo, street_address, bldg_num, city, state_abb, zip_code, dfac_phnumber, flash_msg1, flash_msg2, bf_hours,
    lu_hours, dn_hours, bch_hours, sup_hours, order_timebf, order_timelu, order_timedn, order_timebch, order_timesup) VALUES 
    ('Warrior Inn Restaurant', 'https://scontent.fhnl3-1.fna.fbcdn.net/v/t39.30808-6/302019523_506178674851223_6673869223261237771_n.jpg?_nc_cat=106&ccb=1-7&_nc_sid=efb6e6&_nc_ohc=GxG43QF0P-AAX-A2VnK&_nc_ht=scontent.fhnl3-1.fna&oh=00_AfBimAUvpkKRP7dn9Az1p_kIs1-C-WvL_GfmLGjCfjXf4A&oe=65B061F7',
     '2085 Aleshire Ave', 'BLDG 2085', 'Schofield Barracks', 'HI', 96857, '(808) 655-1062', 'Good morning Warriors!! The Warrior Inn is back in business!', 'Delicious lucky charm pancakes all week!',
     '0730 - 0900', '1130 -1300', '1700-1830', '0930 - 1230', '1630 - 1800', '0600 - 0830', '0930 - 1230', '1500 - 1800', '0900 - 1200', '1500 - 1730'),
    ('Wings of Lightning Inn', 'https://scontent.fhnl3-1.fna.fbcdn.net/v/t39.30808-6/279890363_362567642573971_6637802255963741101_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=efb6e6&_nc_ohc=hCHLihVoD0sAX9TloFD&_nc_oc=AQntU_J5lHnwlzUjg8PacAgxZ0Uo-M0dgTHOXjui0S6gV3h-zgvDeiUDL6EVMDKuN8MAMrOdAedRGQfpBb4Ve5Vk&_nc_ht=scontent.fhnl3-1.fna&oh=00_AfAwrQi4Sygilv34aCjElLlR5mt5Ye0kCmKoj0SfpY9gvw&oe=65B1135E',
     '1129 Wright Ave', 'Bldg. 102', 'Wheeler Army Airfield', 'HI', 96854, '(808) 656-2504', 'Welcome to the Award-Winning Wings of Lightning Warrior Restaurant!', 'Special romantic dinner menu planned for February 2024...stay tuned!',
     '0730 - 0900', '1130 -1300', '1700-1830', '0930 - 1230', '1630 - 1800', '0600 - 0830', '0930 - 1230', '1500 - 1800', '0900 - 1200', '1500 - 1730');

INSERT INTO cooks (dfac_id, username, password, rank, fname, lname, dodid, email, profile_pic, is_admin, is_manager, update_menu, update_hours, update_meals) VALUES
    (1, 'manager1', 'passwordCook', 'SSG', 'Martha', 'Sundam', '8686868686', 'msundam@fake.mail', 'https://www.ziprecruiter.com/svc/fotomat/public-ziprecruiter/cms/914979826GeneralManager.jpg=ws1280x960',
     FALSE, TRUE, TRUE, TRUE, TRUE),
    (1, 'cook11', 'passwordCook11', 'SGT', 'Blaine', 'Tibshirani', '1112234456', 'btibi@fake.mail', NULL, FALSE, FALSE, TRUE, FALSE, FALSE),
    (1, 'cook12', 'passwordCook12', 'SGT', 'William', 'Glasgow', '1112234476', 'wtibi@fake.mail', NULL, FALSE, FALSE, FALSE, TRUE, FALSE),
    (1, 'cook13', 'passwordCook13', 'SPC', 'Mary', 'Stolzfus', '1112234459', 'mtibi@fake.mail', NULL, FALSE, FALSE, FALSE, FALSE, TRUE),
    (NULL, 'generalmanager', 'generalManager', 'MSG', 'Janice', 'Miller', '9992234458', 'jmiller@fake.mail', 'https://www.shutterstock.com/image-photo/closeup-on-businessman-holding-card-260nw-581019652.jpg',
     TRUE, TRUE, TRUE, TRUE, TRUE),
     (2, 'manager2', 'passwordCook', 'SFC', 'Tyrone', 'Marshall', '9797979797', 'tmarshall@fake.mail', 'https://cdn-icons-png.flaticon.com/512/7414/7414124.png', FALSE, TRUE, TRUE, TRUE, TRUE),
     (2, 'cook21', 'passwordCook21', 'SGT', 'Oscar', 'Mallard', '9797979123', 'oshall@fake.mail', 'https://cdn-icons-png.flaticon.com/512/7414/7414124.png', FALSE, FALSE, TRUE, FALSE, FALSE),
     (2, 'cook22', 'passwordCook22', 'SPC', 'Helen', 'Roback', '4321979797', 'hshall@fake.mail', 'https://cdn-icons-png.flaticon.com/512/7414/7414124.png', FALSE, FALSE, FALSE, TRUE, FALSE),
     (2, 'cook23', 'passwordCook23', 'SPC', 'Moses', 'Layfield', '9797555797', 'mshall@fake.mail', 'https://cdn-icons-png.flaticon.com/512/7414/7414124.png', FALSE, FALSE, FALSE, FALSE, TRUE);

INSERT INTO items (menu_item, food_type, recipe_code, description, color_code, sodium_level) VALUES
    ('BACON 3PC', 'PROTEIN', 'L-002-00', 'EVERYDAY MENU', 'RED', 'MODERATE'),
    ('TURKEY LINKS 2LINKS', 'PROTEIN', 'L-200-01', 'MONDAY MENU 1', 'RED', 'LOW'),
    ('CREAMED BEEF 5.25OZ', 'GRAVY', 'L-030-00', 'MONDAY MENU 1', 'YELLOW', 'MODERATE'),
    ('STEAMED WHITE RICE 6OZ', 'STARCH', 'E-006-00', 'MONDAY MENU 1', 'YELLOW', 'LOW'),
    ('HOME FRIED POTATOES 3.75OZ', 'STARCH', 'Q-047-00', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('SCRAMBLED EGGS 2.25OZ', 'PROTEIN', 'F-010-00', 'MONDAY MENU 1', 'YELLOW', 'LOW'),
    ('BOILED EGGS 2EGGS', 'PROTEIN', 'F-004-51', 'MONDAY MENU 1', 'YELLOW', 'LOW'),
    ('GRITS 6OZ', 'STARCH', 'E-002-00', 'MONDAY MENU 1', 'YELLOW', 'LOW'),
    ('BISCUITS 1EA', 'STARCH', 'D-300-01', 'MONDAY MENU 1', 'RED', 'MODERATE'),
    ('FRENCH TOAST 2SLICE', 'STARCH', 'D-022-01', 'MONDAY MENU 1', 'GREEN', 'MODERATE'),
    ('SMOOTHIE BAR', 'BAR', NULL, 'MONDAY MENU 1', 'WHITE', NULL),
    ('BROCCOLI W SAUTEED ONION', 'VEG', 'Q-105-00', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('LASAGNA 10OZ', 'PROTEIN', 'L-025-01', 'MONDAY MENU 1', 'YELLOW', 'HIGH'),
    ('HERBED BAKED CHICKEN BREAST 4OZ', 'PROTEIN', 'L-143-05', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('ROSEMARY POTATOES 3OZ', 'STARCH', 'Q-070-00', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('RICE PILAF 4.5OZ', 'STARCH', 'E-008-00', 'MONDAY MENU 1', 'YELLOW', 'MODERATE'),
    ('ASPARAGUS 2.75OZ', 'VEG', 'Q-100-52', 'MONDAY MENU 1', 'GREEN', 'MODERATE'),
    ('STEAMED CALIFORNIA BLEND 3.25OZ', 'VEG', 'Q-310-00', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('TOASTED GARLIC BREAD 2SLICE', 'STARCH', 'D-007-00', 'MONDAY MENU 1', 'RED', 'MODERATE'),
    ('CREAM OF BROCCOLI SOUP 9OZ', 'SOUP', 'P-014-01', 'MONDAY MENU 1', 'YELLOW', 'HIGH'),
    ('CHICKEN PAN GRAVY 2OZ', 'GRAVY', 'O-016-52', 'MONDAY MENU 1', 'RED', 'HIGH'),
    ('POTATO BAR', 'BAR', NULL, 'MONDAY MENU 1', 'WHITE', NULL),
    ('ITALIAN PASTA SALAD 2.25OZ', 'SALAD', 'M-029-00', 'MONDAY MENU 1', 'YELLOW', 'LOW'),
    ('SPAGHETTI 8OZ', 'PROTEIN', 'L-038-01', 'MONDAY MENU 1', 'YELLOW', 'MODERATE'),
    ('HERBED BAKED FISH 5OZ', 'PROTEIN', 'L-119-04', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('INSTANT MASHED POTATOES 6OZ', 'STARCH', 'Q-057-00', 'MONDAY MENU 1', 'GREEN', 'MODERATE'),
    ('STEAMED BROCCOLI 2.75OZ', 'VEG', 'Q-105-00', 'MONDAY MENU 1', 'GREEN', 'LOW'),
    ('CORN OBRIEN 4OZ', 'VEG', 'Q-027-01', 'MONDAY MENU 1', 'YELLOW', 'MODERATE'),
    ('HOT ROLLS 2ROLLS', 'STARCH', 'D-033-01', 'MONDAY MENU 1', 'YELLOW', 'MODERATE'),
    ('BROWN PAN GRAVY 2OZ', 'GRAVY', 'O-016-01', 'MONDAY MENU 1', 'YELLOW', 'HIGH'),
    ('MINESTRONE SOUP 8OZ', 'SOUP', 'P-007-01', 'MONDAY MENU 1', 'GREEN', 'HIGH'),
    ('SAUSAGE PATTIES 2PATTY', 'PROTEIN', 'L-089-03', 'TUESDAY MENU 2', 'RED', 'HIGH'),
    ('TURKEY BACON 3PC', 'PROTEIN', 'L-180-02', 'TUESDAY MENU 2', 'RED', 'MODERATE'),
    ('OATMEAL 6OZ', 'STARCH', 'E-001-00', 'TUESDAY MENU 2', 'GREEN', 'LOW'),
    ('PANCAKE 2PAN', 'STARCH', 'D-025-05', 'TUESDAY MENU 2', 'YELLOW', 'MODERATE'),
    ('SAUTEED SPINACH W ONIONS 5.25OZ', 'VEG', 'Q-121-50', 'TUESDAY MENU 2', 'GREEN', 'HIGH'),
    ('BEEF ENCHILADAS 2PC', 'PROTEIN', 'L-063-00', 'TUESDAY MENU 2', 'YELLOW', 'HIGH'),
    ('MEXICAN CHICKEN BREAST 4OZ', 'PROTEIN', 'L-143-04', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('SPANISH RICE 6OZ', 'STARCH', 'E-009-551', 'TUESDAY MENU 2', 'YELLOW', 'MODERATE'),
    ('PAPRIKA BUTTERED POTATOES 4.25OZ', 'STARCH', 'Q-033-01', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('ROASTED ZUCCHINI 3.5OZ', 'VEG', 'Q-122-01', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('MEXICAN CORN 4OZ', 'VEG', 'Q-027-02', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('CORN BREAD 1PC', 'STARCH', 'D-015-00', 'TUESDAY MENU 2', 'YELLOW', 'MODERATE'),
    ('CHICKEN TORTILLA SOUP 8OZ', 'SOUP', 'P-025-00', 'TUESDAY MENU 2', 'GREEN', 'HIGH'),
    ('CHILI GRAVY 2OZ', 'GRAVY', 'O-016-03', 'TUESDAY MENU 2', 'YELLOW', 'LOW'),
    ('NACHO BAR', 'BAR', NULL, 'TUESDAY MENU 2', 'WHITE', NULL),
    ('THREE BEAN SALAD 4OZ', 'SALAD', 'M-045-00', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('SAVORY BAKED CHICKEN BREAST 4OZ', 'PROTEIN', 'L-826-00', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('BEEF STEW 11OZ', 'PROTEIN', 'L-022-00', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('INSTANT MASHED POTATOES 6OZ', 'STARCH', 'Q-057-00', 'TUESDAY MENU 2', 'GREEN', 'MODERATE'),
    ('BROWN RICE 6OZ', 'STARCH', 'E-006-50', 'TUESDAY MENU 2', 'GREEN', 'LOW'),
    ('CAULIFLOWER 2.25OZ', 'VEG', 'Q-109-00', 'TUESDAY MENU 2', 'GREEN', 'LOW'),
    ('MIXED VEGETABLES 3OZ', 'VEG', 'Q-126-00', 'TUESDAY MENU 2', 'GREEN', 'LOW'),
    ('VEGETABLE SOUP 8OZ', 'SOUP', 'P-007-00', 'TUESDAY MENU 2', 'GREEN', 'LOW'),
    ('TERIYAKI BEEF & BROCCOLI 4.5OZ', 'PROTEIN', 'L-008-52', ' WEDNESDAY MENU 3', 'YELLOW', 'MODERATE'),
    ('CHICKEN CHOW MEIN, DICED 9.5OZ', 'PROTEIN', 'L-160-00', ' WEDNESDAY MENU 3', 'GREEN', 'HIGH'),
    ('VEGETABLE FRIED RICE', 'STARCH', 'E-007-55', ' WEDNESDAY MENU 3', 'YELLOW', 'MODERATE'),
    ('FRESH MASHED POTATOES 5OZ', 'STARCH', 'Q-048-00', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('PEAS & CARROTS 4.75OZ', 'VEG', 'Q-041-01', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('SAUTEED CABBAGE 2.75OZ', 'VEG', 'Q-012-00', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('GARLIC BUTTERED HOT ROLLS 2ROLLS', 'STARCH', 'D-033-01', ' WEDNESDAY MENU 3', 'YELLOW', 'MODERATE'),
    ('EGG DROP SOUP 8OZ', 'SOUP', 'P-803-00', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('VEGETABLE GRAVY 2OZ', 'GRAVY', 'O-016-08', ' WEDNESDAY MENU 3', 'YELLOW', 'HIGH'),
    ('MONGOLIAN BAR', 'BAR', NULL, ' WEDNESDAY MENU 3', 'WHITE', NULL),
    ('CUCUMBER & ONION SALAD 3.75OZ', 'SALAD', 'M-015-00', ' WEDNESDAY MENU 3', 'GREEN', 'LOW'),
    ('YAKISOBA 11OZ', 'PROTEIN', 'L-062-50', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('CHINESE FIVE SPICE CHICKEN 1PC', 'PROTEIN', 'L-153-50', ' WEDNESDAY MENU 3', 'YELLOW', 'MODERATE'),
    ('OVEN BROWNED POTATOES 4OZ', 'STARCH', 'Q-050-00', ' WEDNESDAY MENU 3', 'GREEN', 'MODERATE'),
    ('CARROTS 2.5OZ', 'VEG', 'Q-108-00', ' WEDNESDAY MENU 3', 'GREEN', 'LOW'),
    ('BEEF AND RICE SOUP 8OZ', 'SOUP', 'P-001-00', ' WEDNESDAY MENU 3', 'GREEN', 'HIGH'),
    ('BARBECUED SPARE RIBS 1PC', 'PROTEIN', 'L-092-00', 'THURSDAY MENU 4', 'YELLOW', 'HIGH'),
    ('HERBED BAKED CHICKEN QTRS', 'PROTEIN', 'L-143-54', 'THURSDAY MENU 4', 'YELLOW', 'MODERATE'),
    ('BLACKENED CATFISH 6OZ', 'PROTEIN', 'L-337-00', 'THURSDAY MENU 4', 'GREEN', 'MODERATE'),
    ('BAKED MACARONI & CHEESE 12.75OZ', 'STARCH', 'T-002-01', 'THURSDAY MENU 4', 'YELLOW', 'HIGH'),
    ('CANDIED SWEET POTATOES 5.5OZ', 'STARCH', 'Q-067-00', 'THURSDAY MENU 4', 'RED', 'MODERATE'),
    ('COLLARD GREENS 4OZ', 'VEG', 'Q-029-53', 'THURSDAY MENU 4', 'GREEN', 'MODERATE'),
    ('CORN ON THE COB 1PC', 'VEG', 'Q-111-00', 'THURSDAY MENU 4', 'GREEN', 'LOW'),
    ('CHICKEN NOODLE SOUP 8OZ', 'SOUP', 'P-002-01', 'THURSDAY MENU 4', 'GREEN', 'HIGH'),
    ('POTATO SALAD 5.75OZ', 'SALAD', 'M-040-00', 'THURSDAY MENU 4', 'GREEN', 'MODERATE'),
    ('HERBED BAKED FISH 5OZ', 'PROTEIN', 'L-119-04', 'THURSDAY MENU 4', 'GREEN', 'LOW'),
    ('MEATLOAF 5.5OZ', 'PROTEIN', 'L-035-00', 'THURSDAY MENU 4', 'YELLOW', 'MODERATE'),
    ('GARLIC ROASTED POTATOES 3.24OZ', 'STARCH', 'Q-070-00', 'THURSDAY MENU 4', 'GREEN', 'LOW'),
    ('NOODLES JEFFERSON 3.75OZ', 'STARCH', 'E-012-00', 'THURSDAY MENU 4', 'RED', 'MODERATE'),
    ('CORN 4OZ', 'VEG', 'Q-110-00', 'THURSDAY MENU 4', 'GREEN', 'LOW'),
    ('CREAM OF MUSHROOM SOUP 8.5OZ', 'SOUP', 'P-014-00', 'THURSDAY MENU 4', 'YELLOW', 'HIGH'),
    ('PINEAPPLE CHICKEN 1PC', 'PROTEIN', 'L-157-50', 'FRIDAY MENU 5', 'YELLOW', 'HIGH'),
    ('ROAST PORK LOIN 4OZ', 'PROTEIN', 'L-081-01', 'FRIDAY MENU 5', 'GREEN', 'MODERATE'),
    ('PINEAPPLE RICE W CILANTRO 6OZ', 'STARCH', 'S-100-15', 'FRIDAY MENU 5', 'YELLOW', 'LOW'),
    ('CAULIFLOWER AU GRATIN 6OZ', 'VEG', 'Q-018-00', 'FRIDAY MENU 5', 'YELLOW', 'MODERATE'),
    ('WING BAR', 'BAR', NULL, 'FRIDAY MENU 5', 'WHITE', NULL),
    ('MACARONI SALAD 5OZ', 'SALAD', 'M-034-00', 'FRIDAY MENU 5', 'YELLOW', 'LOW'),
    ('SWEET & SOUR PORK 8.5OZ', 'PROTEIN', 'L-082-00', 'FRIDAY MENU 5', 'YELLOW', 'HIGH'),
    ('GRILLED CARIBBEAN CHICKEN BREAST 3OZ', 'PROTEIN', 'L-305-01', 'FRIDAY MENU 5', 'GREEN', 'LOW'),
    ('PARSLEY BUTTERED POTATOES 4.25OZ', 'STARCH', 'Q-033-00', 'FRIDAY MENU 5', 'GREEN', 'MODERATE'),
    ('TOSSED GREEN RICE 6OZ', 'STARCH', 'E-005-02', 'FRIDAY MENU 5', 'YELLOW', 'LOW'),
    ('TOMATO SOUP 8OZ', 'SOUP', 'P-006-00', 'FRIDAY MENU 5', 'YELLOW', 'HIGH'),
    ('GARLIC BUTTER FISH 4OZ', 'PROTEIN', 'L-119-01', 'SATURDAY MENU 6', 'GREEN', 'LOW'),
    ('ROAST BEEF CARVED 4OZ', 'PROTEIN', 'L-005-00', 'SATURDAY MENU 6', 'YELLOW', 'MODERATE'),
    ('GINGER GLAZED CARROTS 4.25OZ', 'VEG', 'Q-017-01', 'SATURDAY MENU 6', 'YELLOW', 'MODERATE'),
    ('ITALIAN MEATBALLS 3.75OZ', 'PROTEIN', 'L-353-02', 'SATURDAY MENU 6', 'YELLOW', 'MODERATE'),
    ('PARMESAN FISH 5OZ', 'PROTEIN', 'L-032-51', 'SATURDAY MENU 6', 'YELLOW', 'MODERATE'),
    ('BAKED HAM CARVED 4OZ', 'PROTEIN', 'L-069-00', 'SUNDAY MENU 7', 'YELLOW', 'MODERATE'),
    ('ROASTED BRUSSEL SPROUTS 3.25OZ', 'VEG', 'Q-106-50', 'SUNDAY MENU 7', 'GREEN', 'MODERATE'),
    ('ROASTED CARROTS 4.75OZ', 'VEG', '1-108-52', 'SUNDAY MENU 7', 'GREEN', 'MODERATE'),
    ('SALISBURY STEAK 1PC', 'PROTEIN', 'L-037-00', 'SUNDAY MENU 7', 'RED', 'HIGH'),
    ('SZECHWAN CHICKEN BREAST 1PC', 'PROTEIN', 'L-159-51', 'SUNDAY MENU 7', 'YELLOW', 'MODERATE'),
    ('CAJUN BAKED FISH 4OZ', 'PROTEIN', 'L-119-53', 'SUNDAY MENU 7', 'GREEN', 'MODERATE'),
    ('RED BEANS & RICE 8OZ', 'STARCH', 'E-010-00', 'SUNDAY MENU 7', 'YELLOW', 'HIGH'),
    ('CALICO CORN 4OZ', 'VEG', 'Q-027-00', 'SUNDAY MENU 7', 'YELLOW', 'LOW'),
    ('PEAS 4OZ', 'VEG', 'Q-016-01', 'SUNDAY MENU 7', 'GREEN', 'LOW'),
    ('HAMBURGER', 'SHORT-ORDER', NULL, 'EVERYDAY', 'YELLOW', 'MODERATE'),
    ('FRENCH-FRIES', 'SHORT-ORDER', NULL, 'EVERYDAY', 'YELLOW', 'HIGH'),
    ('CHOCOLATE CAKE', 'BAR', NULL, 'DESSERT', 'RED', 'LOW'),
    ('APPLE PIE', 'BAR', NULL, 'DESSERT', 'YELLOW', 'LOW'),
    ('COFFEE', 'BAR', NULL, 'BEVERAGE', 'WHITE', NULL),
    ('ORANGE JUICE', 'BAR', NULL, 'BEVERAGE', 'WHITE', NULL),
    ('SODA FOUNTAIN', 'BAR', NULL, 'BEVERAGE', 'RED', 'MODERATE'),
    ('ICED TEA', 'BAR', NULL, 'BEVERAGE', 'WHITE', NULL),
    ('WATER', 'BAR', NULL, 'BEVERAGE', 'WHITE', NULL);

INSERT INTO meals (dfac_id, meal_name, description, type, price, img_pic) VALUES
    (1, 'BK #1', 'Bacon and scrambled eggs with home fried potatoes and coffee', 'breakfast', 4.30, 'https://www.sheknows.com/wp-content/uploads/2018/08/eggs_and_bacon_n8mwmd.jpeg'),
    (1, 'BK #2', 'Sausage patties with gravy, oatmeal, spinach, and orange juice', 'breakfast', 4.30, 'https://www.onegreenplanet.org/wp-content/uploads/2019/09/d-4.jpg'),
    (1, 'Lunch #1', 'Mexican chicken breast and spanish rice with roasted zucchini and fountain beverage', 'lunch', 6.85, 'https://www.101cookingfortwo.com/wp-content/uploads/2013/09/chicken-and-rice-on-white-plate-480x270.jpg'),
    (1, 'Lunch #2', 'Teriyaki beef & broccoli with mashed potatoes, peas, and carrots. Includes garlic buttered hot rolls and iced tea.', 'lunch', 6.85, 'https://images.everyplate.com/f_auto,fl_lossy,q_auto/everyplate_s3/image/5c893f82e3f3391b22374102-a3175a68.jpg'),
    (1, 'Dinner #1', 'Spaghetti and corn oBrien with hot rolls and minestrone soup. Choice of beverage.', 'dinner', 5.85, 'https://www.thisisnotdietfood.com/wp-content/uploads/2022/11/onepotspaghetti-02square-735x735.jpg'),
    (1, 'Dinner #2', 'Savory baked chicken breast with pan gravy, brown rice, and mixed vegetables. Choice of drink', 'dinner', 5.85, 'https://mojo.generalmills.com/api/public/content/JV75T_2jNkaFViEwLeo4ow_gmi_hi_res_jpeg.jpeg?v=fcaedb34&t=466b54bb264e48b199fc8e83ef1136b4'),
    (1, 'Dinner #3', 'Short-order burger and fries with fountain beverage', 'dinner', 5.85, 'https://i0.wp.com/www.aspicyperspective.com/wp-content/uploads/2020/07/best-hamburger-patties-1.jpg?resize=1200%2C675&ssl=1'),
    (1, 'The Brunch Meal', 'Three pieces of bacon, two pancakes, parsley buttered potatoes, roasted carrots, and cream of mushroom soup. Includes choice of beverage.',
        'brunch', 7.65, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvSClEdvEmxolfPLdHtHDyHHhXRp79WJz1rQ&usqp=CAU'),
    (1, 'Supper Supreme','Carved roast beef with chicken pan gravy, jefferson noodles, asparagus and corn bread, with cream of broccoli soup and choice of drink.', 'supper',
        9.35, 'https://i0.wp.com/www.thedaintygreenapron.com/wp-content/uploads/2019/11/IMG_6454-scaled-e1647207342792.jpg?fit=750%2C818&ssl=1'),
    (2, 'BK #1', 'Boiled eggs and pancakes with steamed white rice, spinach, and orange juice', 'breakfast', 4.30, 'https://www.sisboomblog.com/wp-content/uploads/2013/05/Chard+Pancakes+with+Egg-1+copy-2.jpg'),
    (2, 'BK #2', 'Turkey links and grits with broccoli, a biscuit and coffee', 'breakfast', 4.30, 'https://media.istockphoto.com/id/981331944/photo/turkey-sausage-links-and-a-biscuit.jpg?s=1024x1024&w=is&k=20&c=Edfy5Y0E9lveqx2YqN0N81eY7Ud8Ko92hp1uQ_GIAGY='),
    (2, 'Lunch #1', 'Roast pork loin and pineapple rice with mixed vegetables and fountain beverage', 'lunch', 6.85, 'https://marleyspoon.com/media/recipes/54294/main_photos/large/hoisin-b41983c2f44f8b943e04753b512d59cb.jpeg'),
    (2, 'Lunch #2', 'Blackened catfish with baked macaroni & cheese, collard greens, corn bread, and iced tea.', 'lunch', 6.85, 'https://thelansingjournal.com/wp-content/uploads/2023/09/Dixie-Kitchen_5487e_1200-1068x752.jpg'),
    (2, 'Dinner #1', 'Meatloaf and garlic roasted potatoes with asparagus and minestrone soup. Choice of drink', 'dinner', 5.85, 'https://www.notenoughcinnamon.com/wp-content/uploads/2019/09/5-Spice-Chicken-Vegetable-Stir-Fry-6.jpg'),
    (2, 'Dinner #2', 'Chinese five spice chicken, rice pilaf, and a steamed California vegetables blend. Choice of drink', 'dinner', 5.85, 'https://mojo.generalmills.com/api/public/content/JV75T_2jNkaFViEwLeo4ow_gmi_hi_res_jpeg.jpeg?v=fcaedb34&t=466b54bb264e48b199fc8e83ef1136b4'),
    (2, 'Dinner #3', 'Short-order burger and fries with fountain beverage', 'dinner', 5.85, 'https://i0.wp.com/www.aspicyperspective.com/wp-content/uploads/2020/07/best-hamburger-patties-1.jpg?resize=1200%2C675&ssl=1'),
    (2, 'The Brunch Meal', 'Three pieces of bacon, two pancakes, parsley buttered potatoes, roasted carrots, and cream of mushroom soup. Includes choice of beverage.',
        'brunch', 7.65, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvSClEdvEmxolfPLdHtHDyHHhXRp79WJz1rQ&usqp=CAU'),
    (2, 'Supper Supreme','Carved roast beef with chicken pan gravy, jefferson noodles, asparagus and corn bread, with cream of broccoli soup and choice of drink.', 'supper',
        9.35, 'https://i0.wp.com/www.thedaintygreenapron.com/wp-content/uploads/2019/11/IMG_6454-scaled-e1647207342792.jpg?fit=750%2C818&ssl=1');

INSERT INTO meal_items (meal_id, item_id) VALUES
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'BACON 3PC')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SCRAMBLED EGGS 2.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'HOME FRIED POTATOES 3.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'COFFEE')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SAUSAGE PATTIES 2PATTY')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'BROWN PAN GRAVY 2OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'OATMEAL 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SAUTEED SPINACH W ONIONS 5.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ORANGE JUICE')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BOILED EGGS 2EGGS')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'PANCAKE 2PAN')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'STEAMED WHITE RICE 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'SAUTEED SPINACH W ONIONS 5.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ORANGE JUICE')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'TURKEY LINKS 2LINKS')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'GRITS 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BROCCOLI W SAUTEED ONION')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BISCUITS 1EA')),
    ((SELECT id FROM meals WHERE meal_name = 'BK #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'COFFEE')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'MEXICAN CHICKEN BREAST 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SPANISH RICE 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ROASTED ZUCCHINI 3.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SODA FOUNTAIN')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'TERIYAKI BEEF & BROCCOLI 4.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'FRESH MASHED POTATOES 5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'PEAS & CARROTS 4.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'GARLIC BUTTERED HOT ROLLS 2ROLLS')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ICED TEA')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ROAST PORK LOIN 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'PINEAPPLE RICE W CILANTRO 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'MIXED VEGETABLES 3OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'SODA FOUNTAIN')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BLACKENED CATFISH 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BAKED MACARONI & CHEESE 12.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'COLLARD GREENS 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CORN BREAD 1PC')),
    ((SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ICED TEA')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SPAGHETTI 8OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'CORN OBRIEN 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'HOT ROLLS 2ROLLS')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'MINESTRONE SOUP 8OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SAVORY BAKED CHICKEN BREAST 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'BROWN PAN GRAVY 2OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'BROWN RICE 6OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'MIXED VEGETABLES 3OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'HAMBURGER')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'FRENCH-FRIES')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'SODA FOUNTAIN')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'MEATLOAF 5.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'GARLIC ROASTED POTATOES 3.24OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ASPARAGUS 2.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #1' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'MINESTRONE SOUP 8OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CHINESE FIVE SPICE CHICKEN 1PC')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'RICE PILAF 4.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #2' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'STEAMED CALIFORNIA BLEND 3.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'HAMBURGER')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'FRENCH-FRIES')),
    ((SELECT id FROM meals WHERE meal_name = 'Dinner #3' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'SODA FOUNTAIN')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'BACON 3PC')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'PANCAKE 2PAN')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'PARSLEY BUTTERED POTATOES 4.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ROASTED CARROTS 4.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'CREAM OF MUSHROOM SOUP 8.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'BACON 3PC')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'PANCAKE 2PAN')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'PARSLEY BUTTERED POTATOES 4.25OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ROASTED CARROTS 4.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'The Brunch Meal' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CREAM OF MUSHROOM SOUP 8.5OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ROAST BEEF CARVED 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'CHICKEN PAN GRAVY 2OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'NOODLES JEFFERSON 3.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'ASPARAGUS 2.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'CORN BREAD 1PC')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 1), (SELECT id FROM items WHERE menu_item = 'CREAM OF BROCCOLI SOUP 9OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ROAST BEEF CARVED 4OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CHICKEN PAN GRAVY 2OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'NOODLES JEFFERSON 3.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'ASPARAGUS 2.75OZ')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CORN BREAD 1PC')),
    ((SELECT id FROM meals WHERE meal_name = 'Supper Supreme' AND dfac_id = 2), (SELECT id FROM items WHERE menu_item = 'CREAM OF BROCCOLI SOUP 9OZ'));

INSERT INTO nutrition (menu_item_id, calories, protein, carbs, fat) VALUES
    ((SELECT id FROM items where menu_item = 'BACON 3PC'), '125', '9g', '0.3g', '9.9g'),
    ((SELECT id FROM items where menu_item = 'SCRAMBLED EGGS 2.25OZ'), '122', '6g', '1.1g', '7g'),
    ((SELECT id FROM items where menu_item = 'HOME FRIED POTATOES 3.75OZ'), '154', '3.5g', '48g', '16.8g'),
    ((SELECT id FROM items where menu_item = 'SAUSAGE PATTIES 2PATTY'), '447', '25g', '2g', '37g'),
    ((SELECT id FROM items where menu_item = 'BROWN PAN GRAVY 2OZ'), '76', '1g', '3g', '3g'),
    ((SELECT id FROM items where menu_item = 'OATMEAL 6OZ'), '119', '4.2g', '21g', '2.4g'),
    ((SELECT id FROM items where menu_item = 'SAUTEED SPINACH W ONIONS 5.25OZ'), '126', '3g', '8g', '10g'),
    ((SELECT id FROM items where menu_item = 'BOILED EGGS 2EGGS'), '155', '12g', '1.2g', '10g'),
    ((SELECT id FROM items where menu_item = 'PANCAKE 2PAN'), '231', '3.6g', '16g', '5.4g'),
    ((SELECT id FROM items where menu_item = 'STEAMED WHITE RICE 6OZ'), '147', '4.6g', '47g', '0.6g'),
    ((SELECT id FROM items where menu_item = 'TURKEY LINKS 2LINKS'), '99', '8g', '2g', '7g'),
    ((SELECT id FROM items where menu_item = 'GRITS 6OZ'), '102', '2.4g', '22g', '0.2g'),
    ((SELECT id FROM items where menu_item = 'BROCCOLI W SAUTEED ONION'), '39', '1.7g', '4.6g', '2.8g'),
    ((SELECT id FROM items where menu_item = 'BISCUITS 1EA'), '177', '3.3g', '19.4g', '8.6g'),
    ((SELECT id FROM items WHERE menu_item = 'MEXICAN CHICKEN BREAST 4OZ'), '164', '22.5g', '3.1g', '6.6g'),
    ((SELECT id FROM items WHERE menu_item = 'SPANISH RICE 6OZ'), '170', '3.6g', '29.9g', '8.4g'),
    ((SELECT id FROM items WHERE menu_item = 'ROASTED ZUCCHINI 3.5OZ'), '82', '5.5g', '9.6g', '4.1g'),
    ((SELECT id FROM items WHERE menu_item = 'TERIYAKI BEEF & BROCCOLI 4.5OZ'), '290', '22.8g', '11.2g', '17.5g'),
    ((SELECT id FROM items WHERE menu_item = 'FRESH MASHED POTATOES 5OZ'), '151', '2.5g', '22.5g', '5.7g'),
    ((SELECT id FROM items WHERE menu_item = 'PEAS & CARROTS 4.75OZ'), '115', '7.4g', '24.2g', '1g'),
    ((SELECT id FROM items WHERE menu_item = 'GARLIC BUTTERED HOT ROLLS 2ROLLS'), '90', '1.8g', '9g', '4.5g'),
    ((SELECT id FROM items WHERE menu_item = 'ROAST PORK LOIN 4OZ'), '191', '29.5g', '0g', '7.6g'),
    ((SELECT id FROM items WHERE menu_item = 'PINEAPPLE RICE W CILANTRO 6OZ'), '220', '3.7g', '41g', '2.6g'),
    ((SELECT id FROM items WHERE menu_item = 'MIXED VEGETABLES 3OZ'), '96', '3.7g', '19.1g', '0.5g'),
    ((SELECT id FROM items WHERE menu_item = 'BLACKENED CATFISH 6OZ'), '283', '30g', '4.6g', '16.4g'),
    ((SELECT id FROM items WHERE menu_item = 'BAKED MACARONI & CHEESE 12.75OZ'), '651', '35.9g', '65.3g', '26.1g'),
    ((SELECT id FROM items WHERE menu_item = 'COLLARD GREENS 4OZ'), '43', '3.6g', '7.5g', '1g');

INSERT INTO orders (customer_id, dfac_id, comments) VALUES
    ((SELECT id FROM customers WHERE username = 'customer1'), 1, NULL),
    ((SELECT id FROM customers WHERE username = 'customer2'), 1, 'Sprite please'),
    ((SELECT id FROM customers WHERE username = 'customer3'), 2, 'Picking up food for me and my team'),
    ((SELECT id FROM customers WHERE username = 'customer4'), 2, 'Pick-up by Bilbo Baggins for Arthur Pendragon'),
    ((SELECT id FROM customers WHERE username = 'customer5'), 2, 'Pick-up by Bilbo Baggins for Auntie Ursula');

INSERT INTO order_meals (order_id, meal_id, quantity, special_instructions) VALUES
    ((SELECT id FROM orders WHERE dfac_id = 1 AND comments IS NULL), (SELECT id FROM meals WHERE meal_name = 'BK #1' AND dfac_id = 1), 1, NULL),
    ((SELECT id FROM orders WHERE dfac_id = 1 AND comments = 'Sprite please'), (SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 1), 1, 'Thank you so much!'),
    ((SELECT id FROM orders WHERE dfac_id = 2 AND comments = 'Picking up food for me and my team'), (SELECT id FROM meals WHERE meal_name = 'Lunch #1' AND dfac_id = 2), 1, 'Could I get cherry coke with my meal?'),
    ((SELECT id FROM orders WHERE dfac_id = 2 AND comments = 'Pick-up by Bilbo Baggins for Arthur Pendragon'), (SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), 1, NULL),
    ((SELECT id FROM orders WHERE dfac_id = 2 AND comments = 'Pick-up by Bilbo Baggins for Auntie Ursula'), (SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), 1, NULL);

INSERT INTO surrogates (order_id, customer_id, surrogate_id, meal_id, authorization_doc) VALUES
    ((SELECT id FROM orders WHERE dfac_id = 2 AND comments = 'Pick-up by Bilbo Baggins for Arthur Pendragon'), (SELECT id FROM customers WHERE username = 'customer4'), (SELECT id FROM customers WHERE username = 'customer3'),
        (SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), 'SignedAuthorization.pdf'),
    ((SELECT id FROM orders WHERE dfac_id = 2 AND comments = 'Pick-up by Bilbo Baggins for Auntie Ursula'), (SELECT id FROM customers WHERE username = 'customer5'), (SELECT id FROM customers WHERE username = 'customer3'),
        (SELECT id FROM meals WHERE meal_name = 'Lunch #2' AND dfac_id = 2), 'SignedAuthorization.pdf');